twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
       api_key: '%env(APP_CURRENCY_KEY)%'
       project_name: '%env(PROJECT_NAME)%'
       copy_right_text: '%env(COPY_RIGHT_TEXT)%'
